language: node_js
sudo: false
node_js:
- "8"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
after_script:
- codecov
before_install:
- npm i -g codecov
branches:
  only:
  - master
cache:
  directories:
  - node_modules
env:
- TRAVIS=travis CXX=g++-4.8
script:
- npm test
