version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install npm globals
          command: sudo npm i -g ava codecov
      - restore_cache:
          key: cache--{{ checksum "package.json" }}
      - run:
          name: Install npm
          command: npm i
      - save_cache:
          key: cache--{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Test
          command: npm test
      - run:
          name: Upload test reports
          command: codecov
